### PR TITLE
fix panels for Tabs in create and update views. fixes #85

### LINKED ISSUE #85: Respect Panels and Panel order on edit page
On my User Resource I use one Tabs-Component and one standard Nova Panel, like this:

```
    public function fields(Request $request)
    {
        return [
            new Tabs(__('Personal Details'), $this->getPersonalDetailsFields($request)),
            new Panel(__('Game Details'), $this->getGameDetailsFields($request)),
        ];
    }
```

On the detail page, two cards are displayed, with the Personal Details at the top and the Game Details at the bottom, as expected.

On the edit page however, just one card is displayed, with the Game Details at the top, then the tab bar, then the Personal Details fields.  
It looks like [this screenshot](https://user-images.githubusercontent.com/3426944/52180482-13862d80-27e7-11e9-9193-58c5801322b0.png) from potentially related issue #14.

My desired behaviour is for the edit page to look exactly like the detail page, one card for the Tab-component, one card for the Panel-component, in the same order that they are declared in the source code. Is this possible?

### PR DESCRIPTION
**Pull request by elijahworkz**
This fixes the issue in Update or Create view when all tabs panels were bunched into one default. Issue #85 

It also makes 'fieldsOutsideTabs' in FormTabs.vue obsolete as any fields that are not included in Tabs will be shown on default Panel

### CODE REVIEW

File: src/TabsOnEdit.php [hunk 1]
```diff
@@ -177,4 +161,31 @@ private function resolveResource(NovaRequest $request)
 
         return $request->newResource();
     }
+
+    private function assignTabPanels(FieldCollection $fields) 
+    {
+        $non_tab_fields = $tab_panels = [];
```
Comment (RVxLab) [inline src/TabsOnEdit.php:167]: Don't use snake_case. Please run the package's `composer php-cs-fixer`.

File: src/TabsOnEdit.php [hunk 2]
```diff
@@ -177,4 +161,31 @@ private function resolveResource(NovaRequest $request)
...
+                    ];
+                    $tab_panels[$field->panel] = $new_panel;
+                }
+            } else {
+                $non_tab_fields[] = $field;
+            }
+        });
+
+        return new TabsFieldCollection([
+            ...$non_tab_fields,
```
Comment (RVxLab) [inline src/TabsOnEdit.php:187]: As this package still targets PHP 7.1, please use `array_merge` instead.

Using this would require a major bump.

File: src/TabsOnEdit.php [hunk 3]
```diff
@@ -177,4 +161,31 @@ private function resolveResource(NovaRequest $request)
 
         return $request->newResource();
     }
+
+    private function assignTabPanels(FieldCollection $fields) 
+    {
+        $non_tab_fields = $tab_panels = [];
+
+        $fields->each(function($field, $key) use (&$non_tab_fields, &$tab_panels) {
```
Comment (RVxLab) [inline src/TabsOnEdit.php:169]: Refrain from using this many nested if blocks, return early.

**Review by RVxLab — CHANGES_REQUESTED** [review]

File: src/TabsOnEdit.php (hunk 3 above)
Comment (elijahworkz) [reply src/TabsOnEdit.php:169]: @RVxLab I'm not sure I understand this request.

I'm going through the list of ALL fields to see whether or not they need to be left as is (not put into 'tabs' component). But for tabs fields - I wanted to make sure that if there are two or more Tabs() used - that it those fields are assigned properly (there should be as many tabs components as there are Tabs panels)
I can't return here or break - it'll stop assignments for the rest of the block.

Can you please clarify what you meant?

**Comment by elijahworkz** [comment]
@RVxLab I refactored the function to use each() on fields collection. That solved other issues as well.

Please review.

**Review by RVxLab — APPROVED** [review]

**Comment by RVxLab** [comment]
Looks good and seems to work well on Nova 3.21. Thanks for your PR!

One question before I merge though, what exactly do you mean with this?

> It also makes 'fieldsOutsideTabs' in FormTabs.vue obsolete as any fields that are not included in Tabs will be shown on default Panel

Are you saying that [lines 3 through 16](https://github.com/eminiarts/nova-tabs/blob/master/resources/js/components/FormTabs.vue#L3) can be removed?

If yes, then perfect. Otherwise, please explain.

**Comment by elijahworkz** [comment]
@RVxLab yes.
that bit in template and also in the script - [line 96](https://github.com/eminiarts/nova-tabs/blob/c642ae4d909507663f521bb86e24a6775abb57d9/resources/js/components/FormTabs.vue#L96) and also [lines 114 - 117](https://github.com/eminiarts/nova-tabs/blob/c642ae4d909507663f521bb86e24a6775abb57d9/resources/js/components/FormTabs.vue#L114)

**Comment by RVxLab** [comment]
I'll fix that on my end. Thanks again!
